spring:
  application:
    name: HelloClient


eureka:
  server:
    enable-self-preservation: false
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
          defaultZone: http://ip-172-31-25-134.us-east-2.compute.internal:8761/eureka
server:
  port: 5002

  instance:
    leaseRenewalIntervalInSeconds: 10
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}