FROM openjdk:8-jdk-alpine
VOLUME /tmp
EXPOSE 8080

ARG JAR_FILE=target/notification-client-1.0.0-SNAPSHOT.jar
COPY ${JAR_FILE} notification-client.jar
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/notification-client.jar"]