spring:
  application:
    name: HelloServer


eureka:
  server:
    enable-self-preservation: false
  instance:
    ip-address: ${HOST_NAME}
    preferIpAddress: true
    non-secure-port: 80
  client:
    fetch-registry: false
    register-with-eureka: true
    serviceUrl:
          defaultZone: http://ec2-18-222-101-42.us-east-2.compute.amazonaws.com:8761/eureka/
server:
  port: 8080

  instance:
    leaseRenewalIntervalInSeconds: 10
    metadataMap:
      hostname: ${eureka.instance.ip-address}:${spring.application.name}:${server.port}