FROM openjdk:8-jdk-alpine
VOLUME /tmp
EXPOSE 8080

ARG JAR_FILE=target/feign-eureka-hello-server-0.0.2-SNAPSHOT.jar
COPY ${JAR_FILE} feign-eureka-hello-server.jar
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/feign-eureka-hello-server.jar"]