FROM openjdk:8-jdk-alpine
VOLUME /tmp
EXPOSE 8761

ARG JAR_FILE=target/aws-eureka-server-1.0.0-SNAPSHOT.jar
COPY ${JAR_FILE} aws-eureka-server.jar
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/aws-eureka-server.jar"]