eureka:
  server:
    enable-self-preservation: false
  instance:
    hostname: ${HOST_NAME}
  client:
    fetch-registry: false
    register-with-eureka: false
    defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
server:
  port: 8761

